### ISSUE TITLE
pybind_library_test doesn't compile

### ISSUE THREAD

**Issue by jiawen** [pybind/pybind11_bazel#36]
`pybind_library_test` constructs a `cc_test` with `deps` that include `"//util/python:python_impl"` and `"//util/python:test_main"`. Those don't exist anywhere - I imagine they're Google internal dependencies that leaked out :).

**Comment by rwgk** [comment]
> Same here. That rule is broken.

Sadly: that's a fair assessment. Fixes welcome. I'll review quickly.

Background: Work on this repo is currently not staffed, we're just muddling through TBH, but we are actively using it for http://github.com/pybind/pybind11_abseil and http://github.com/pybind/pybind11_protobuf.

**Comment by virgile-hogman** [comment]
Thanks for the answer.
Background: I have a problem of linkage with pybind 2.10.x when using a `cc_test` rule with many, many unresolved symbols:
```
...mytest.cpp:function _Py_DECREF: error: undefined reference to '_Py_Dealloc'
...mytest.cpp:function pybind11::type_error::set_error() const: error: undefined reference to 'PyExc_TypeError'
...mytest.cpp:function bool pybind11::detail::string_caster<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false>::load_raw<char>(std::enable_if<std::is_same<char, char>::value, pybind11::handle>::type): error: undefined reference to 'PyByteArray_Size'
```
I manage to build some `pybind_extension` but not the `cc_test`... though that worked fine until pybind 2.9.2.
So I hoped that `pybind_library_test` could help. I tried to replicate the same options without success.

The test is linked with `deps = ["@local_config_python//:python_embed"]`
With pybind 2.9.2 or lower it also worked with `deps = ["@python38//:libpython"]`. It drags a new .so file that I didn't needed with `python_embed` so I guess `python_embed` is better. With that method and pybind 2.10.x it produces less unresolved symbols but it's still failing.

The python toolchain is configured as follows:
```
# rules_python
load("@rules_python//python:repositories.bzl", "python_register_toolchains")
python_register_toolchains(
    name = "python38",
    # Available versions are listed in @rules_python//python:versions.bzl.
    # We recommend using the same version your team is already standardized on.
    python_version = "3.8",
)
load("@python38//:defs.bzl", "interpreter")
...
# pybind11_bazel
load("@pybind11_bazel//:python_configure.bzl", "python_configure")
python_configure(
    name = "local_config_python",
    python_interpreter_target = interpreter,
)
```
I still don't understand what the `cc_test` is supposed to link. Any suggestion is much welcome.

**Comment by virgile-hogman** [comment]
From pybind11:
> On Linux and macOS, it’s better to (intentionally) not link against libpython. The symbols will be resolved when the extension library is loaded into a Python binary. This is preferable because you might have several different installations of a given Python version (e.g. the system-provided Python ...

This makes perfectly sense for an pybind extension and it's consistent to what I wrote earlier. The question is for a C++ test binary, what to link against? Couldn't it be resolved in the same manner at runtime?

**Comment by virgile-hogman** [comment]
I realized I should rather use `@pybind11//:pybind11_embed` but it gives the same result, unresolved symbols with 2.10.x, works fine with 2.9.2.

**Comment by jiawen** [comment]
> > Same here. That rule is broken.
> 
> 
> 
> Sadly: that's a fair assessment. Fixes welcome. I'll review quickly.
L> 
> 
> 
> Background: Work on this repo is currently not staffed, we're just muddling through TBH, but we are actively using it for http://github.com/pybind/pybind11_abseil and http://github.com/pybind/pybind11_protobuf.

Understood! I'm a Xoogler and Bazel/abseil/pybind superfan. I am happy to contribute a fix (once I find some spare cycles). The current config is working fine in my various polyglot repos.

**Comment by junyer** [comment]
Do we have to **_remove_** `//util/python:python_impl` and `//util/python:test_main` or **_replace_** them with... something else?

**Comment by manu8989** [comment]
@junyer I just removed `//util/python:python_impl` and `//util/python:test_main`.
But I also have the issue of many undefined references, for example:
```
...
bazel-out/k8-fastbuild/bin/_solib_k8/[...].so: error: undefined reference to 'PyByteArray_Size'
bazel-out/k8-fastbuild/bin/_solib_k8/[...].so: error: undefined reference to 'PyByteArray_AsString'
bazel-out/k8-fastbuild/bin/_solib_k8/[...].so: error: undefined reference to 'PyType_IsSubtype'
bazel-out/k8-fastbuild/bin/_solib_k8/[...].so: error: undefined reference to 'PyByteArray_Type'
bazel-out/k8-fastbuild/bin/_solib_k8/[...].so: error: undefined reference to 'PyUnicode_AsUTF8AndSize'
bazel-out/k8-fastbuild/bin/_solib_k8/[...].so: error: undefined reference to 'PyStatus_IsError'
bazel-out/k8-fastbuild/bin/_solib_k8/[...].so: error: undefined reference to 'PyRun_SimpleStringFlags'
bazel-out/k8-fastbuild/bin/_solib_k8/[...].so: error: undefined reference to 'PyConfig_Clear'
bazel-out/k8-fastbuild/bin/_solib_k8/[...].so: error: undefined reference to 'Py_InitializeFromConfig'
bazel-out/k8-fastbuild/bin/_solib_k8/[...].so: error: undefined reference to 'PyStatus_Exception'
bazel-out/k8-fastbuild/bin/_solib_k8/[...].so: error: undefined reference to 'PyConfig_SetBytesArgv'
...
```
Did anyone find a solution for this?

**Comment by manu8989** [comment]
Thank you! That worked :ok_hand: @junyer

**Comment by junyer** [comment]
Great, thanks for confirming! I will fix the `pybind_library_test` rule shortly as discussed. :)
